version: "3.8"

services:
    db:
        image: postgres:15-alpine
        container_name: fr-db
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust

    backend:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        image: dev-backend
        container_name: fr-backend
        restart: always
        volumes:
            - staticfiles:/backend/static/
        depends_on:
            - db
        secrets:
            - backend_secrets
        networks:
            default:
                ipv4_address: 192.168.0.3

    frontend:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        image: dev-frontend
        container_name: fr-frontend
        depends_on:
            - backend
        networks:
            default:
                ipv4_address: 192.168.0.4

    nginx:
        build:
            context: ./nginx/
            dockerfile: ./Dockerfile
        image: dev-nginx
        container_name: fr-nginx
        volumes:
            - staticfiles:/static/
        ports:
            - "8080:80"
        depends_on:
            - frontend
        networks:
            default:
                ipv4_address: 192.168.0.5

volumes:
    staticfiles:
    postgres_data:

networks:
    default:
        name: fr_network
        ipam:
            config:
                - subnet: 192.168.0.0/24

secrets:
    backend_secrets:
        file: backend/backend_secrets
